package es.sealsign.bss;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 15-06-2015
//
//---------------------------------------------------


import java.util.EnumSet;
import java.util.UUID;


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class BSBBasicHttpBinding_IBiometricSignatureServiceBasic
{
    interface BSBIWcfMethod
    {
        BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url = "http://localhost/SealSignBSSService/BiometricSignatureServiceBasic.svc/BB"; // Default
    String userName = "domain\\user";
    String password = "password";

    int timeOut=60000;
    public List<HeaderProperty> httpHeaders = new ArrayList<HeaderProperty>();
    public boolean enableLogging;

    BSBIServiceEvents callback;
    public BSBBasicHttpBinding_IBiometricSignatureServiceBasic(){}

    public BSBBasicHttpBinding_IBiometricSignatureServiceBasic (BSBIServiceEvents callback)
    {
        this.callback = callback;
        addBasicHeader();
    }
    public BSBBasicHttpBinding_IBiometricSignatureServiceBasic(BSBIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
        addBasicHeader();
    }

    public BSBBasicHttpBinding_IBiometricSignatureServiceBasic(BSBIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
        addBasicHeader();
    }
    
    private void addBasicHeader(){
        httpHeaders.add(new HeaderProperty("Authorization", "Basic " +      
        		org.kobjects.base64.Base64.encode((userName+ ":" + password).getBytes())));
    }
    
    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected BSBExtendedSoapSerializationEnvelope createEnvelope()
    {
        BSBExtendedSoapSerializationEnvelope envelope= new BSBExtendedSoapSerializationEnvelope(BSBExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,BSBExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }  
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,BSBExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public void HeartBeat( ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "HeartBeat");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/HeartBeat",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< Void>> HeartBeatAsync()
    {
        return executeAsync(new BSBFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                HeartBeat( );
                return null;
            }
        }) ;
    }
    
    public BSBBiometricSignatureBeginResponseBasic BeginSignature(final BSBEnums.SignatureProfile signatureProfile,final BSBEnums.BiometricSignatureType biometricSignatureType,final String id,final String account,final EnumSet<BSBEnums.BiometricSignatureFlags> biometricOptions,final BSBBiometricSignatureParameters biometricParameters,final EnumSet<BSBEnums.SignatureFlags> options,final BSBSignatureParameters parameters,final byte[] detachedSignature,final byte[] signingDocument ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (BSBBiometricSignatureBeginResponseBasic)execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","biometricParameters",new BSBBiometricSignatureParameters().getClass());
                __envelope.addMapping("http://tempuri.org/","parameters",new BSBSignatureParameters().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BeginSignature");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureProfile";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signatureProfile!=null?signatureProfile.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricSignatureType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricSignatureType!=null?biometricSignatureType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="account";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(account!=null?account:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricOptions";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(BSBEnums.BiometricSignatureFlags.getFlagValue(biometricOptions));
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricParameters";
                __info.type=BSBBiometricSignatureParameters.class;
                __info.setValue(biometricParameters!=null?biometricParameters:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="options";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(BSBEnums.SignatureFlags.getFlagValue(options));
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="parameters";
                __info.type=BSBSignatureParameters.class;
                __info.setValue(parameters!=null?parameters:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="detachedSignature";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(detachedSignature!=null?org.kobjects.base64.Base64.encode(detachedSignature):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signingDocument";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signingDocument!=null?org.kobjects.base64.Base64.encode(signingDocument):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (BSBBiometricSignatureBeginResponseBasic)getResult(BSBBiometricSignatureBeginResponseBasic.class,__result,"BeginSignatureResult",__envelope);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/BeginSignature",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< BSBBiometricSignatureBeginResponseBasic>> BeginSignatureAsync(final BSBEnums.SignatureProfile signatureProfile,final BSBEnums.BiometricSignatureType biometricSignatureType,final String id,final String account,final EnumSet<BSBEnums.BiometricSignatureFlags> biometricOptions,final BSBBiometricSignatureParameters biometricParameters,final EnumSet<BSBEnums.SignatureFlags> options,final BSBSignatureParameters parameters,final byte[] detachedSignature,final byte[] signingDocument)
    {
        return executeAsync(new BSBFunctions.IFunc< BSBBiometricSignatureBeginResponseBasic>() {
            public BSBBiometricSignatureBeginResponseBasic Func() throws java.lang.Exception {
                return BeginSignature( signatureProfile,biometricSignatureType,id,account,biometricOptions,biometricParameters,options,parameters,detachedSignature,signingDocument);
            }
        });
    }
    
    public BSBBiometricSignatureBeginResponseBasic BeginSignatureProvider(final String id,final String account,final String uri,final String providerParameter,final byte[] document ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (BSBBiometricSignatureBeginResponseBasic)execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "BeginSignatureProvider");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="account";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(account!=null?account:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="uri";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(uri!=null?uri:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="providerParameter";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(providerParameter!=null?providerParameter:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="document";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(document!=null?org.kobjects.base64.Base64.encode(document):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (BSBBiometricSignatureBeginResponseBasic)getResult(BSBBiometricSignatureBeginResponseBasic.class,__result,"BeginSignatureProviderResult",__envelope);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/BeginSignatureProvider",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< BSBBiometricSignatureBeginResponseBasic>> BeginSignatureProviderAsync(final String id,final String account,final String uri,final String providerParameter,final byte[] document)
    {
        return executeAsync(new BSBFunctions.IFunc< BSBBiometricSignatureBeginResponseBasic>() {
            public BSBBiometricSignatureBeginResponseBasic Func() throws java.lang.Exception {
                return BeginSignatureProvider( id,account,uri,providerParameter,document);
            }
        });
    }
    
    public byte[] EndSignature(final UUID instance,final byte[] biometricState ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (byte[])execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "EndSignature");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="instance";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(instance!=null?instance:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricState";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricState!=null?org.kobjects.base64.Base64.encode(biometricState):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object j = __soap.getProperty("EndSignatureResult");
                return BSBHelper.getBinary(j,false);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/EndSignature",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< byte[]>> EndSignatureAsync(final UUID instance,final byte[] biometricState)
    {
        return executeAsync(new BSBFunctions.IFunc< byte[]>() {
            public byte[] Func() throws java.lang.Exception {
                return EndSignature( instance,biometricState);
            }
        });
    }
    
    public byte[] EndSignatureProvider(final UUID instance,final byte[] biometricState,final String uri,final String providerParameter,final Boolean returnSignedDocument ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (byte[])execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "EndSignatureProvider");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="instance";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(instance!=null?instance:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricState";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricState!=null?org.kobjects.base64.Base64.encode(biometricState):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="uri";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(uri!=null?uri:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="providerParameter";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(providerParameter!=null?providerParameter:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="returnSignedDocument";
                __info.type=PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(returnSignedDocument!=null?returnSignedDocument:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object j = __soap.getProperty("EndSignatureProviderResult");
                return BSBHelper.getBinary(j,false);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/EndSignatureProvider",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< byte[]>> EndSignatureProviderAsync(final UUID instance,final byte[] biometricState,final String uri,final String providerParameter,final Boolean returnSignedDocument)
    {
        return executeAsync(new BSBFunctions.IFunc< byte[]>() {
            public byte[] Func() throws java.lang.Exception {
                return EndSignatureProvider( instance,biometricState,uri,providerParameter,returnSignedDocument);
            }
        });
    }
    
    public BSBBiometricSignatureVerification Verify(final BSBEnums.SignatureProfile signatureProfile,final BSBEnums.BiometricSignatureType biometricSignatureType,final String id,final String account,final EnumSet<BSBEnums.BiometricVerificationFlags> biometricOptions,final BSBBiometricVerificationParameters biometricParameters,final byte[] biometricState,final byte[] detachedSignature,final byte[] document ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (BSBBiometricSignatureVerification)execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","biometricParameters",new BSBBiometricVerificationParameters().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "Verify");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureProfile";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signatureProfile!=null?signatureProfile.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricSignatureType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricSignatureType!=null?biometricSignatureType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="id";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(id!=null?id:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="account";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(account!=null?account:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricOptions";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(BSBEnums.BiometricVerificationFlags.getFlagValue(biometricOptions));
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricParameters";
                __info.type=BSBBiometricVerificationParameters.class;
                __info.setValue(biometricParameters!=null?biometricParameters:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricState";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricState!=null?org.kobjects.base64.Base64.encode(biometricState):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="detachedSignature";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(detachedSignature!=null?org.kobjects.base64.Base64.encode(detachedSignature):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="document";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(document!=null?org.kobjects.base64.Base64.encode(document):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (BSBBiometricSignatureVerification)getResult(BSBBiometricSignatureVerification.class,__result,"VerifyResult",__envelope);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/Verify",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< BSBBiometricSignatureVerification>> VerifyAsync(final BSBEnums.SignatureProfile signatureProfile,final BSBEnums.BiometricSignatureType biometricSignatureType,final String id,final String account,final EnumSet<BSBEnums.BiometricVerificationFlags> biometricOptions,final BSBBiometricVerificationParameters biometricParameters,final byte[] biometricState,final byte[] detachedSignature,final byte[] document)
    {
        return executeAsync(new BSBFunctions.IFunc< BSBBiometricSignatureVerification>() {
            public BSBBiometricSignatureVerification Func() throws java.lang.Exception {
                return Verify( signatureProfile,biometricSignatureType,id,account,biometricOptions,biometricParameters,biometricState,detachedSignature,document);
            }
        });
    }
    
    public BSBBiometricSignatureVerification GetInfoFromBiometricState(final BSBEnums.SignatureProfile signatureProfile,final UUID instance,final byte[] biometricState,final byte[] document ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (BSBBiometricSignatureVerification)execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetInfoFromBiometricState");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureProfile";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signatureProfile!=null?signatureProfile.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="instance";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(instance!=null?instance:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="biometricState";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(biometricState!=null?org.kobjects.base64.Base64.encode(biometricState):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="document";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(document!=null?org.kobjects.base64.Base64.encode(document):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (BSBBiometricSignatureVerification)getResult(BSBBiometricSignatureVerification.class,__result,"GetInfoFromBiometricStateResult",__envelope);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/GetInfoFromBiometricState",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< BSBBiometricSignatureVerification>> GetInfoFromBiometricStateAsync(final BSBEnums.SignatureProfile signatureProfile,final UUID instance,final byte[] biometricState,final byte[] document)
    {
        return executeAsync(new BSBFunctions.IFunc< BSBBiometricSignatureVerification>() {
            public BSBBiometricSignatureVerification Func() throws java.lang.Exception {
                return GetInfoFromBiometricState( signatureProfile,instance,biometricState,document);
            }
        });
    }
    
    public BSBBiometricSignatureVerification GetInfo(final BSBEnums.SignatureProfile signatureProfile,final byte[] document ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (BSBBiometricSignatureVerification)execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetInfo");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureProfile";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signatureProfile!=null?signatureProfile.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="document";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(document!=null?org.kobjects.base64.Base64.encode(document):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (BSBBiometricSignatureVerification)getResult(BSBBiometricSignatureVerification.class,__result,"GetInfoResult",__envelope);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/GetInfo",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< BSBBiometricSignatureVerification>> GetInfoAsync(final BSBEnums.SignatureProfile signatureProfile,final byte[] document)
    {
        return executeAsync(new BSBFunctions.IFunc< BSBBiometricSignatureVerification>() {
            public BSBBiometricSignatureVerification Func() throws java.lang.Exception {
                return GetInfo( signatureProfile,document);
            }
        });
    }
    
    public byte[] SyncOfflineSignatures(final BSBEnums.SignatureProfile signatureProfile,final BSBArrayOfOfflineBiometricSignature offlineSignatures,final byte[] detachedSignature,final byte[] signingDocument ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (byte[])execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","offlineSignatures",new BSBArrayOfOfflineBiometricSignature().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SyncOfflineSignatures");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signatureProfile";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signatureProfile!=null?signatureProfile.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="offlineSignatures";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(offlineSignatures!=null?offlineSignatures:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="detachedSignature";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(detachedSignature!=null?org.kobjects.base64.Base64.encode(detachedSignature):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signingDocument";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signingDocument!=null?org.kobjects.base64.Base64.encode(signingDocument):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object j = __soap.getProperty("SyncOfflineSignaturesResult");
                return BSBHelper.getBinary(j,false);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/SyncOfflineSignatures",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< byte[]>> SyncOfflineSignaturesAsync(final BSBEnums.SignatureProfile signatureProfile,final BSBArrayOfOfflineBiometricSignature offlineSignatures,final byte[] detachedSignature,final byte[] signingDocument)
    {
        return executeAsync(new BSBFunctions.IFunc< byte[]>() {
            public byte[] Func() throws java.lang.Exception {
                return SyncOfflineSignatures( signatureProfile,offlineSignatures,detachedSignature,signingDocument);
            }
        });
    }
    
    public byte[] SyncOfflineSignaturesProvider(final BSBArrayOfOfflineBiometricSignatureProvider offlineSignatures,final byte[] signingDocument,final Boolean returnSignedDocument ) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (byte[])execute(new BSBIWcfMethod()
        {
            @Override
            public BSBExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              BSBExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","offlineSignatures",new BSBArrayOfOfflineBiometricSignatureProvider().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SyncOfflineSignaturesProvider");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="offlineSignatures";
                __info.type=PropertyInfo.VECTOR_CLASS;
                __info.setValue(offlineSignatures!=null?offlineSignatures:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="signingDocument";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(signingDocument!=null?org.kobjects.base64.Base64.encode(signingDocument):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="returnSignedDocument";
                __info.type=PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(returnSignedDocument!=null?returnSignedDocument:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(BSBExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object j = __soap.getProperty("SyncOfflineSignaturesProviderResult");
                return BSBHelper.getBinary(j,false);
            }
        },"http://tempuri.org/IBiometricSignatureServiceBasic/SyncOfflineSignaturesProvider",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, BSBOperationResult< byte[]>> SyncOfflineSignaturesProviderAsync(final BSBArrayOfOfflineBiometricSignatureProvider offlineSignatures,final byte[] signingDocument,final Boolean returnSignedDocument)
    {
        return executeAsync(new BSBFunctions.IFunc< byte[]>() {
            public byte[] Func() throws java.lang.Exception {
                return SyncOfflineSignaturesProvider( offlineSignatures,signingDocument,returnSignedDocument);
            }
        });
    }

    
    protected java.lang.Object execute(BSBIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        BSBExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, BSBOperationResult< T>>  executeAsync(final BSBFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, BSBOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected BSBOperationResult< T> doInBackground(Void... params) {
                BSBOperationResult< T> result = new BSBOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(BSBOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,BSBExtendedSoapSerializationEnvelope envelope)
    {

        if(fault.detail!=null && fault.detail.getChildCount()>0)
        {
            Element detailsNode=(Element)fault.detail.getChild(0);
            try
            {
                SoapObject exceptionObject = null;
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
                exceptionObject=envelope.GetExceptionDetail(detailsNode,"http://schemas.datacontract.org/2004/07/SealSignBSSService","SealSignDSSFaultContract");
                if (exceptionObject != null)
                {
                    return new BSBSealSignDSSFaultContract(exceptionObject,envelope);
                }
            }
            catch (java.lang.Exception e)
            {
                e.printStackTrace();
            }
        }
        return new java.lang.Exception(fault.faultstring);
    }
}


