package es.sealsign.bss;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 15-06-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class BSBBiometricSignatureVerification extends AttributeContainer implements KvmSerializable
{
    
    public BSBSignatureVerification dssResult;
    
    public BSBEnums.BiometricVerificationResult result;
    
    public BSBArrayOfBiometricSignatureReference signatures=new BSBArrayOfBiometricSignatureReference();

    public BSBBiometricSignatureVerification ()
    {
    }

    public BSBBiometricSignatureVerification (java.lang.Object paramObj,BSBExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("dssResult"))
        {	
	        java.lang.Object j = soapObject.getProperty("dssResult");
	        this.dssResult = (BSBSignatureVerification)__envelope.get(j,BSBSignatureVerification.class);
        }
        if (soapObject.hasProperty("result"))
        {	
	        java.lang.Object obj = soapObject.getProperty("result");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.result = BSBEnums.BiometricVerificationResult.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BSBEnums.BiometricVerificationResult){
                this.result = (BSBEnums.BiometricVerificationResult)obj;
            }    
        }
        if (soapObject.hasProperty("signatures"))
        {	
	        java.lang.Object j = soapObject.getProperty("signatures");
	        this.signatures = new BSBArrayOfBiometricSignatureReference(j,__envelope);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.dssResult!=null?this.dssResult:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.result!=null?this.result.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.signatures!=null?this.signatures:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = BSBSignatureVerification.class;
            info.name = "dssResult";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "result";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "signatures";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
