package es.sealsign.bss;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 15-06-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class BSBBiometricSignatureReference extends AttributeContainer implements KvmSerializable
{
    
    public Double score;
    
    public String signatureAccount;
    
    public String signatureID;
    
    public BSBEnums.SignatureProfile signatureProfile;
    
    public BSBEnums.BiometricVerificationStatus signatureStatus;
    
    public BSBEnums.BiometricSignatureType signatureType;
    
    public String signatureUserName;
    
    public org.joda.time.DateTime signingTime;
    
    public BSBTimestampReference timestamp;
    
    public String version;

    public BSBBiometricSignatureReference ()
    {
    }

    public BSBBiometricSignatureReference (java.lang.Object paramObj,BSBExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("score"))
        {	
	        java.lang.Object obj = soapObject.getProperty("score");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.score = new Double(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Double){
                this.score = (Double)obj;
            }    
        }
        if (soapObject.hasProperty("signatureAccount"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureAccount");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureAccount = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.signatureAccount = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signatureID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.signatureID = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signatureProfile"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureProfile");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureProfile = BSBEnums.SignatureProfile.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BSBEnums.SignatureProfile){
                this.signatureProfile = (BSBEnums.SignatureProfile)obj;
            }    
        }
        if (soapObject.hasProperty("signatureStatus"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureStatus");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureStatus = BSBEnums.BiometricVerificationStatus.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BSBEnums.BiometricVerificationStatus){
                this.signatureStatus = (BSBEnums.BiometricVerificationStatus)obj;
            }    
        }
        if (soapObject.hasProperty("signatureType"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureType");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureType = BSBEnums.BiometricSignatureType.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BSBEnums.BiometricSignatureType){
                this.signatureType = (BSBEnums.BiometricSignatureType)obj;
            }    
        }
        if (soapObject.hasProperty("signatureUserName"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signatureUserName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signatureUserName = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.signatureUserName = (String)obj;
            }    
        }
        if (soapObject.hasProperty("signingTime"))
        {	
	        java.lang.Object obj = soapObject.getProperty("signingTime");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.signingTime = BSBHelper.ConvertFromWebService(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof org.joda.time.DateTime){
                this.signingTime = (org.joda.time.DateTime)obj;
            }    
        }
        if (soapObject.hasProperty("timestamp"))
        {	
	        java.lang.Object j = soapObject.getProperty("timestamp");
	        this.timestamp = (BSBTimestampReference)__envelope.get(j,BSBTimestampReference.class);
        }
        if (soapObject.hasProperty("version"))
        {	
	        java.lang.Object obj = soapObject.getProperty("version");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.version = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.version = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.score!=null?this.score:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.signatureAccount!=null?this.signatureAccount:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.signatureID!=null?this.signatureID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.signatureProfile!=null?this.signatureProfile.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.signatureStatus!=null?this.signatureStatus.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.signatureType!=null?this.signatureType.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.signatureUserName!=null?this.signatureUserName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.signingTime!=null?this.signingTime.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.timestamp!=null?this.timestamp:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.version!=null?this.version:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 10;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = Double.class;
            info.name = "score";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureAccount";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureID";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureProfile";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureStatus";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureType";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signatureUserName";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "signingTime";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==8)
        {
            info.type = BSBTimestampReference.class;
            info.name = "timestamp";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "version";
            info.namespace= "http://schemas.datacontract.org/2004/07/SealSignBSSTypes";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
