package es.sealsign.bss;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 15-06-2015
//
//---------------------------------------------------



public interface BSBIServiceEvents
{
    public void Starting();
    public void Completed(BSBOperationResult result);
}
